In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
trozo_de_arr = arr[0:5]

In [8]:
trozo_de_arr[:]=0

In [9]:
trozo_de_arr

array([0, 0, 0, 0, 0])

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy[:] = 100

In [19]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])