In [1]:
import numpy as np

In [5]:
scalar = np.array(42)
scalar.ndim

0

In [7]:
vector = np.array([1,2,3])
vector.ndim

1

In [9]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [12]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


3

## Agregar o eliminar dimensiones
Se hace con la notación ndmin luego de declarar la lista dentro del np.array[]

In [14]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expandido = np.expand_dims(np.array([1,2,3]), axis=0)
print(expandido)
expandido.ndim

In [19]:
print(vector, vector.ndim)
vector_2=np.squeeze(vector)
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [21]:
practice=np.array([1,2,3], ndmin=31)
print(practice)
practice.ndim

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


32

In [23]:
practice =np.expand_dims([1,2,3], axis=0)
print(practice)
practice.ndim

[[1 2 3]]


2