In [3]:
import numpy as np

In [4]:
arr=np.random.randint(1,20,10)
print(arr)

[ 9 12 17  8 18 15 16  8  7 14]


In [9]:
matriz = arr.reshape(2,5)
matriz

array([[ 9, 12, 17,  8, 18],
       [15, 16,  8,  7, 14]])

In [11]:
print(arr.max())

18


In [17]:
matriz.argmax(0)

array([1, 1, 0, 0, 0])

In [20]:
matriz.min(0)

array([ 9, 12,  8,  7, 14])

Del pico más alto al pico más bajo hay una diferencia de 11


In [22]:
arr

array([ 9, 12, 17,  8, 18, 15, 16,  8,  7, 14])

In [21]:
arr.ptp()

11

Especificar el percentil con el que se está trabajando

In [24]:
np.percentile(arr,50)

13.0

Para ordenar:

In [26]:
arr.sort()
arr

array([ 7,  8,  8,  9, 12, 14, 15, 16, 17, 18])

Mediana:

In [27]:
np.median(arr)

13.0

In [28]:
np.median(matriz,0)

array([10.5, 11.5, 12. , 13. , 15. ])

In [29]:
np.std(arr)

3.9293765408777004

In [30]:
np.var(arr)

15.440000000000001

Media:

In [35]:
matriz

array([[ 7,  8,  8,  9, 12],
       [14, 15, 16, 17, 18]])

In [36]:
np.mean(matriz,0)

array([10.5, 11.5, 12. , 13. , 15. ])

Concatenar  array a + b:

In [42]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [45]:
a.ndim
b.ndim


1

In [47]:
b = np.expand_dims(b,axis=0)

In [48]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])