In [1]:
import numpy as np

In [4]:
lista = list(range(1,3))
lista

[1, 2]

In [5]:
lista * 2

[1, 2, 1, 2]

In [8]:
arr = np.arange(0,10)
arr2 = arr.copy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Operaciones

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
1 / arr

/tmp/ipykernel_92293/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matriz_2 = matriz.copy()

In [18]:
matriz + matriz_2


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [19]:
np.matmul(matriz,matriz_2.T)

array([[ 30,  80],
       [ 80, 255]])

In [20]:
matriz @ matriz_2.T

array([[ 30,  80],
       [ 80, 255]])