In [1]:
import numpy as np

In [7]:
arr = np.random.randint(1,10,(3,2))

In [5]:
arr.shape

(3, 2)

In [10]:
arr.reshape(2,3)

array([[2, 4, 6],
       [6, 3, 6]])

In [12]:
np.reshape(arr,(1,6))

array([[2, 4, 6, 6, 3, 6]])

In [13]:
np.reshape(arr,(2,3),'C')

array([[2, 4, 6],
       [6, 3, 6]])

In [14]:
np.reshape(arr,(2,3),'F')

array([[2, 3, 6],
       [6, 4, 6]])

In [15]:
np.reshape(arr,(2,3),'A')

array([[2, 4, 6],
       [6, 3, 6]])