In [21]:
import numpy as np

In [22]:
arr=np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [23]:
arr=np.array([1,2,3,4], dtype='float64')
print(arr)

[1. 2. 3. 4.]


In [24]:
arr

array([1., 2., 3., 4.])

In [25]:
arr = arr.astype(np.float64)

In [26]:
arr

array([1., 2., 3., 4.])

In [27]:
arr = np.array([1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([ True,  True,  True,  True])

In [28]:
arr = np.array([1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'1', b'2', b'3', b'4'], dtype='|S21')

In [29]:
arr = np.array(["1","2","3","4"])
arr = arr.astype(np.int8)
arr

array([1, 2, 3, 4], dtype=int8)